# Template taken from: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Rust.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# Use cargo to test the project
test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    # Install rustfmt see https://rustrepo.com/repo/rust-lang-docker-rust-rust-deployment #4 for why
    - rustup component add rustfmt
    - cargo fmt --all -- --check # Enforce linting rules
    - cargo test --workspace --verbose # Build and test

